# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying a version
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run